PROCEDURES = [
    {
        "id": "KB-0001",
        "module": "MWD Coach",
        "title": "No Sync / Weak Pulse Troubleshooting",
        "verification_status": "Verified - Field Use",
        "source": "SDI MWD field manual + field case review",
        "revision": "Rev A",
        "last_reviewed": "2026-07-01",
        "reviewed_by": "Cesar / SME",
        "steps": [
            "Confirm pumps are on and flow is stable.",
            "Check standpipe pressure stability.",
            "Verify pulse pressure is visible on oscilloscope or pressure trace.",
            "Check active mud pump with driller.",
            "Ask about valve/seat condition if pressure is noisy.",
            "Switch pumps if instability continues.",
            "Only adjust decoder filters after hydraulic issue is ruled out.",
        ],
        "field_notes": [
            "Do not immediately change FFT when visible pulses are present.",
            "Pump noise can appear as decode failure even when tool is pulsing.",
            "Document pump number, SPP, flow, pulse pressure, and sync status.",
        ],
    },
    {
        "id": "KB-0002",
        "module": "MWD Coach",
        "title": "Decode Confidence / Correlation Drop",
        "verification_status": "Draft - Needs Manual Page Verification",
        "source": "MWDRun observations + field troubleshooting logic",
        "revision": "Rev A",
        "last_reviewed": "2026-07-01",
        "reviewed_by": "Pending SME",
        "steps": [
            "Check decode confidence trend.",
            "Check correlation and correlation margin.",
            "Review oscilloscope waveform quality.",
            "Confirm SPP stability and pulse pressure.",
            "Check for pump changes or flow interruptions.",
            "Verify tool settings match programmed telemetry mode.",
            "Escalate if confidence continues to fall.",
        ],
        "field_notes": [
            "Correlation can degrade before full loss of sync.",
            "Trend changes matter more than a single snapshot.",
        ],
    },
    {
        "id": "KB-0003",
        "module": "MWD Coach",
        "title": "Weak Pulse Pressure",
        "verification_status": "Draft - Needs Manual Page Verification",
        "source": "MWDRun pressure monitoring",
        "revision": "Rev A",
        "last_reviewed": "2026-07-01",
        "reviewed_by": "Pending SME",
        "steps": [
            "Confirm current pulse pressure.",
            "Compare against expected pulse pressure for tool and telemetry settings.",
            "Check flow rate and pump output.",
            "Check for pressure noise masking pulses.",
            "Verify pulser status if available.",
            "Escalate if pulse pressure remains low.",
        ],
        "field_notes": [
            "Low pulse pressure can be hydraulic, mechanical, or software-related.",
            "Always rule out pump/flow instability first.",
        ],
    },
    {
        "id": "KB-0004",
        "module": "MWD Coach",
        "title": "Vibration Risk Troubleshooting",
        "verification_status": "Draft - Needs Manual Page Verification",
        "source": "RSS / MWD vibration monitoring",
        "revision": "Rev A",
        "last_reviewed": "2026-07-01",
        "reviewed_by": "Pending SME",
        "steps": [
            "Identify vibration type: axial, lateral, or torsional.",
            "Compare vibration with RPM, WOB, torque, and ROP trends.",
            "Make small parameter changes only with DD/driller alignment.",
            "Monitor response after each change.",
            "Document before and after values.",
        ],
        "field_notes": [
            "High lateral vibration may indicate whirl.",
            "Stick-slip should be treated as torsional dysfunction.",
        ],
    },
    {
        "id": "HALO-0001",
        "module": "HALO RSS Coach",
        "title": "HFTO Vibration Mitigation",
        "verification_status": "Imported - Needs SME Approval",
        "source": "HALO RSS Appendix B: Vibration Mitigation Flowcharts",
        "revision": "Rev A",
        "last_reviewed": "2026-07-02",
        "reviewed_by": "Pending Scientific Drilling SME",
        "steps": [
            "Trigger: two consecutive Delta Vibes readings greater than 4 g RMS.",
            "Increase bit/surface RPM 5-10% and observe.",
            "If unresolved, increase RPM another 5-10% and observe.",
            "If unresolved, decrease RPM back to original value.",
            "Reduce WOB by 15% and observe; repeat once if needed.",
            "If unresolved, reduce bit RPM 5-10% and observe.",
            "If severe or unresolved, pick up off bottom, allow string torque to unwind, restart at minimum operating parameters, and step parameters up.",
        ],
        "field_notes": [
            "Drill ahead only with improved parameters until out of the trouble zone.",
            "Follow operating limits and DD/company approval before parameter changes.",
        ],
    },
    {
        "id": "HALO-0002",
        "module": "HALO RSS Coach",
        "title": "Bit Whirl / Lateral Vibration Mitigation",
        "verification_status": "Imported - Needs SME Approval",
        "source": "HALO RSS Appendix B + Drilling Optimization Workflow",
        "revision": "Rev A",
        "last_reviewed": "2026-07-02",
        "reviewed_by": "Pending Scientific Drilling SME",
        "steps": [
            "Symptoms: high lateral vibration, increased mean surface torque, reduced ROP, increased shock count.",
            "Decrease bit RPM 5-10%.",
            "Increase WOB 5-10%.",
            "If not reduced, repeat once and observe.",
            "If unresolved, pick up off bottom and allow torque to unwind.",
            "Restart with WOB around 110% of original and RPM at original value.",
            "If still unstable, manage as best possible and consider BHA adjustments.",
        ],
        "field_notes": [
            "HFTO can appear like bit whirl when primary and MWD sensors are both high.",
            "If vibration becomes more severe while following whirl steps, use HFTO mitigation.",
        ],
    },
    {
        "id": "HALO-0003",
        "module": "HALO RSS Coach",
        "title": "Stick Slip / Torsional Vibration Mitigation",
        "verification_status": "Imported - Needs SME Approval",
        "source": "HALO RSS Appendix B + Drilling Optimization Workflow",
        "revision": "Rev A",
        "last_reviewed": "2026-07-02",
        "reviewed_by": "Pending Scientific Drilling SME",
        "steps": [
            "Symptoms: red primary stick-slip indicator, erratic or oscillating surface torque, RPM cycling.",
            "Increase bit RPM 5-10%.",
            "Decrease WOB 5-10%.",
            "If not reduced, repeat once and observe.",
            "If unresolved, pick up off bottom and allow torque to unwind.",
            "Restart around RPM 110% of original and WOB 85% of original.",
            "If still unstable, restart around RPM 50% of original and WOB 75% of original, then gradually increase RPM until stable.",
        ],
        "field_notes": [
            "The stable zone can be a fine balance between lateral and torsional instability.",
            "Use caution when changing parameters.",
        ],
    },
    {
        "id": "OPT-0001",
        "module": "Optimization AI",
        "title": "MSE / ROP Efficiency Screening",
        "verification_status": "Prototype",
        "source": "Engineering calculation prototype",
        "revision": "Rev A",
        "last_reviewed": "2026-07-02",
        "reviewed_by": "Pending SME",
        "steps": [
            "Calculate MSE from WOB, torque, RPM, ROP, and bit size.",
            "Trend MSE against ROP and drilling dysfunction indicators.",
            "If MSE rises while ROP falls, check bit wear, formation change, or vibration dysfunction.",
            "Use MSE as an advisory indicator, not a standalone command.",
        ],
        "field_notes": [
            "MSE thresholds should be tuned by basin, bit type, BHA, and formation.",
        ],
    },
]
