PROCEDURES = [
    {
        "id": "KB-0001",
        "title": "No Sync / Weak Pulse Troubleshooting",
        "verification_status": "Verified - Field Use",
        "source": "SDI MWD field manual + field case review",
        "revision": "Rev A",
        "last_reviewed": "2026-07-01",
        "reviewed_by": "Cesar / SME",
        "steps": [
            "Confirm pumps are on and flow is stable.",
            "Check standpipe pressure stability.",
            "Verify pulse pressure is visible on oscilloscope or pressure trace.",
            "Check active mud pump with driller.",
            "Ask about valve/seat condition if pressure is noisy.",
            "Switch pumps if instability continues.",
            "Only adjust decoder filters after hydraulic issue is ruled out.",
        ],
        "field_notes": [
            "Do not immediately change FFT when visible pulses are present.",
            "Pump noise can appear as decode failure even when tool is pulsing.",
            "Document pump number, SPP, flow, pulse pressure, and sync status.",
        ],
    },
    {
        "id": "KB-0002",
        "title": "Decode Confidence / Correlation Drop",
        "verification_status": "Draft - Needs Manual Page Verification",
        "source": "MWDRun observations + field troubleshooting logic",
        "revision": "Rev A",
        "last_reviewed": "2026-07-01",
        "reviewed_by": "Pending SME",
        "steps": [
            "Check decode confidence trend.",
            "Check correlation and correlation margin.",
            "Review oscilloscope waveform quality.",
            "Confirm SPP stability and pulse pressure.",
            "Check for pump changes or flow interruptions.",
            "Verify tool settings match programmed telemetry mode.",
            "Escalate if confidence continues to fall.",
        ],
        "field_notes": [
            "Correlation can degrade before full loss of sync.",
            "Trend changes matter more than a single snapshot.",
        ],
    },
    {
        "id": "KB-0003",
        "title": "Weak Pulse Pressure",
        "verification_status": "Draft - Needs Manual Page Verification",
        "source": "MWDRun pressure monitoring",
        "revision": "Rev A",
        "last_reviewed": "2026-07-01",
        "reviewed_by": "Pending SME",
        "steps": [
            "Confirm current pulse pressure.",
            "Compare against expected pulse pressure for tool and telemetry settings.",
            "Check flow rate and pump output.",
            "Check for pressure noise masking pulses.",
            "Verify pulser status if available.",
            "Escalate if pulse pressure remains low.",
        ],
        "field_notes": [
            "Low pulse pressure can be hydraulic, mechanical, or software-related.",
            "Always rule out pump/flow instability first.",
        ],
    },
    {
        "id": "KB-0004",
        "title": "Vibration Risk Troubleshooting",
        "verification_status": "Draft - Needs Manual Page Verification",
        "source": "RSS / MWD vibration monitoring",
        "revision": "Rev A",
        "last_reviewed": "2026-07-01",
        "reviewed_by": "Pending SME",
        "steps": [
            "Identify vibration type: axial, lateral, or torsional.",
            "Compare vibration with RPM, WOB, torque, and ROP trends.",
            "Make small parameter changes only with DD/driller alignment.",
            "Monitor response after each change.",
            "Document before and after values.",
        ],
        "field_notes": [
            "High lateral vibration may indicate whirl.",
            "Stick-slip should be treated as torsional dysfunction.",
        ],
    },
]
